### ISSUE TITLE
Publish new package

### ISSUE THREAD

**Issue by acrogenesis** [jonkoops/matomo-tracker#741]
There are several bug fixes that haven't been published to NPM (last publish was 6 months ago v0.5.1). Maybe using a GitHub action to automatically publish the packages on merge to main is the way to go.

I found this example:
https://github.com/azu/lerna-monorepo-github-actions-release

Related issues: #711 #666

**Comment by acrogenesis** [comment]
In the meantime I've published the latest commit (4bd37eef08866c8e5af93864fd98fcfedf2a0f2f) here https://github.com/orgs/valiot/packages?repo_name=matomo-tracker

**Comment by nickchauhan** [comment]
@acrogenesis Unable to install your version

```
npm install @valiot/matomo-tracker-react
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@valiot%2fmatomo-tracker-react - Not found
npm ERR! 404 
npm ERR! 404  '@valiot/matomo-tracker-react@*' is not in this registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

**Comment by acrogenesis** [comment]
@nickchauhan create an `.npmrc` file with the content:
```
@valiot:registry=https://npm.pkg.github.com
```

**Comment by antoine-giret** [comment]
Hello ! Thx for your work ! Any news on this new package ?

**Comment by rpep** [comment]
Hi there,

Thanks a lot for your work on this package - we've found it very useful. Just a note to say that we'd also be very interested in a new update of this package as we now run into the source errors on upgrading to Webpack 5. We did try to install directly from the repository on a commit hash, but couldn't figure out a way to do so because of the subfolder structure.

**Comment by acrogenesis** [comment]
@rpep you can use the package I published on github or do as I did and fork the project and publish the packages. I did that because as you said I also couldn't figure out a way to install using the commit hash because of the structure.

**Comment by pushrbx** [comment]
> In the meantime I've published the latest commit ([4bd37ee](https://github.com/Amsterdam/matomo-tracker/commit/4bd37eef08866c8e5af93864fd98fcfedf2a0f2f)) here https://github.com/orgs/valiot/packages?repo_name=matomo-tracker

This one currently doesn't work, yarn/npm says 401 Unauthorized. I guess the token has expired on it.
```
$ yarn add @valiot/matomo-tracker-react --verbose                                 
yarn add v1.22.18
verbose 0.1806944 Checking for configuration file "C:\\Users\\pushrbx\\WebstormProjects\\test-project\\.npmrc".
verbose 0.1814038 Checking for configuration file "C:\\Users\\pushrbx\\.npmrc".
verbose 0.1819959 Checking for configuration file "C:\\Users\\pushrbx\\scoop\\apps\\nvm\\current\\nodejs\\nodejs\\etc\\npmrc".
verbose 0.1826485 Checking for configuration file "C:\\Users\\pushrbx\\WebstormProjects\\test-project\\.npmrc".
verbose 0.1832573 Checking for configuration file "C:\\Users\\pushrbx\\WebstormProjects\\.npmrc".
verbose 0.1838791 Checking for configuration file "C:\\Users\\pushrbx\\.npmrc".
verbose 0.1844729 Checking for configuration file "C:\\Users\\.npmrc".
verbose 0.1858952 Checking for configuration file "C:\\Users\\pushrbx\\WebstormProjects\\test-project\\.yarnrc".
verbose 0.1865207 Found configuration file "C:\\Users\\pushrbx\\WebstormProjects\\test-project\\.yarnrc".
verbose 0.187135 Checking for configuration file "C:\\Users\\pushrbx\\.yarnrc".
verbose 0.1877563 Found configuration file "C:\\Users\\pushrbx\\.yarnrc".
verbose 0.1884804 Checking for configuration file "C:\\Users\\pushrbx\\scoop\\apps\\nvm\\current\\nodejs\\nodejs\\etc\\yarnrc".
verbose 0.1893958 Checking for configuration file "C:\\Users\\pushrbx\\WebstormProjects\\test-project\\.yarnrc".
verbose 0.1901496 Found configuration file "C:\\Users\\pushrbx\\WebstormProjects\\test-project\\.yarnrc".
verbose 0.1911221 Checking for configuration file "C:\\Users\\pushrbx\\WebstormProjects\\.yarnrc".
verbose 0.1917707 Checking for configuration file "C:\\Users\\pushrbx\\.yarnrc".
verbose 0.1923529 Found configuration file "C:\\Users\\pushrbx\\.yarnrc".
verbose 0.1932763 Checking for configuration file "C:\\Users\\.yarnrc".
verbose 0.2007294 current time: 2022-04-06T12:40:01.644Z
$ node -e "!process.env.npm_config_user_agent.startsWith('yarn/') && !console.log('Use \`npx yarn install\` to install dependencies in this repository\n') && process.exit(1)"
[1/4] Resolving packages...
verbose 0.9164218 Performing "GET" request to "https://npm.pkg.github.com/@valiot%2fmatomo-tracker-react".
verbose 1.3289688 Request "https://npm.pkg.github.com/@valiot%2fmatomo-tracker-react" finished with status code 401.
verbose 1.3530932 Error: Couldn't find package "@valiot/matomo-tracker-react" on the "npm" registry.
    at MessageError.ExtendableBuiltin (C:\Users\pushrbx\scoop\persist\nvm\nodejs\v16.14.0\node_modules\yarn\lib\cli.js:721:66)
    at new MessageError (C:\Users\pushrbx\scoop\persist\nvm\nodejs\v16.14.0\node_modules\yarn\lib\cli.js:750:123)
    at NpmResolver.<anonymous> (C:\Users\pushrbx\scoop\persist\nvm\nodejs\v16.14.0\node_modules\yarn\lib\cli.js:50481:15)
    at Generator.next (<anonymous>)
    at step (C:\Users\pushrbx\scoop\persist\nvm\nodejs\v16.14.0\node_modules\yarn\lib\cli.js:310:30)
    at C:\Users\pushrbx\scoop\persist\nvm\nodejs\v16.14.0\node_modules\yarn\lib\cli.js:321:13
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
error Couldn't find package "@valiot/matomo-tracker-react" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

**Comment by acrogenesis** [comment]
> @nickchauhan create an `.npmrc` file with the content:
> 
> ```
> @valiot:registry=https://npm.pkg.github.com
> ```

@pushrbx try this

**Comment by pushrbx** [comment]
I've tried it both with `.npmrc` and `.yarnrc`, the result is still the same. In the output I can clearly see the following:
```
verbose 1.3289688 Request "https://npm.pkg.github.com/@valiot%2fmatomo-tracker-react" finished with status code 401.
```

**Comment by th0was14** [comment]
what is the problem ? why are we waiting ?

**Comment by jonkoops** [comment]
A new release has been [made available](https://github.com/jonkoops/matomo-tracker/releases/tag/v0.7.0).

**Comment by jonkoops** [comment]
Thanks, I've corrected it!

**Comment by rpep** [comment]
Thanks @jonkoops - that's brill!

**Comment by Lrigh1** [comment]
Fantastic @jonkoops!  I just got back from paternity leave and you have saved the day!  (and @thomasm0 !)
